import { SuppressorKeyT } from "../../store/characterSlice"

export const SuppressorImages:{[Sup in SuppressorKeyT]:string} = {
    '0.0': "",
    '1.1': require("./images/1.webp"),
    '1.2': require("./images/1.webp"),
    '1.3': require("./images/1.webp"),
    '1.4': require("./images/1.webp"),
    '1.5': require("./images/1.webp"),
    '2.1': require("./images/2.webp"),
    '2.2': require("./images/2.webp"),
    '2.3': require("./images/2.webp"),
    '2.4': require("./images/2.webp"),
    '2.5': require("./images/2.webp"),
    '3.1': require("./images/3.webp"),
    '3.2': require("./images/3.webp"),
    '3.3': require("./images/3.webp"),
    '3.4': require("./images/3.webp"),
    '3.5': require("./images/3.webp"),
    '4.1': require("./images/4.webp"),
    '4.2': require("./images/4.webp"),
    '4.3': require("./images/4.webp"),
    '4.4': require("./images/4.webp"),
    '4.5': require("./images/4.webp"),
    '5.1': require("./images/5.webp"),
    '5.2': require("./images/5.webp"),
    '5.3': require("./images/5.webp"),
    '5.4': require("./images/5.webp"),
    '5.5': require("./images/5.webp"),
    '6.1': require("./images/6.webp"),
    '6.2': require("./images/6.webp"),
    '6.3': require("./images/6.webp"),
    '6.4': require("./images/6.webp"),
    '6.5': require("./images/6.webp"),
    '7.1': require("./images/7.webp"),
    '7.2': require("./images/7.webp"),
    '7.3': require("./images/7.webp"),
    '7.4': require("./images/7.webp"),
    '7.5': require("./images/7.webp"),
    '8.1': require("./images/8.webp"),
    '8.2': require("./images/8.webp"),
    '8.3': require("./images/8.webp"),
    '8.4': require("./images/8.webp"),
    '8.5': require("./images/8.webp")
}
